### ISSUE TITLE
Integrate Jenkins into project

### ISSUE THREAD

**Issue by m-smith15** [m-smith15/webdev_flashcards#15]
Integrate Jira/Jenkins into the project for issue tracking!

**Comment by coren-frankel** [comment]
I need to own my confusion about Jira and specifically Jenkins.

Upon more research, I discovered that I had conflated Jira and Jenkins as the same kind of tool and I wanted to split this issue in two. 

Now that I've done some more reading I've come to understand that vercel already provides most of the same services that Jenkins could provide--CI/CD tools. Furthermore, Jenkins is much better suited for developing large scale apps with Docker or another containerization software, and would require Java 11 to run natively on your local machine. It apparently would require quite an amount of studying to learn it--at least in context to webdev flashcards. I'm not even sure it would be possible, but it absolutely is unnecessary.

Suffice to say, Issue #15 is now specifically integrating Jira as a workflow tool.
If Jira is even what I think it is. ☠️

**Comment by coren-frankel** [comment]
Ok, read some more, this time about Jira. While I very much look forward to using a task management software like this, it ain't free. We might as well stick to Trello and/or Google Docs, and github issues for organization and issue tracking. One day soon we'll be paid to learn and use software like Jira but it's not for webdev flashcards.

Closing issue #15 -- and not with Jira's nifty issue tracking software.
