### ISSUE TITLE
Replace all Bootstrap SVG icons with icon font HTML elements

### ISSUE THREAD

**Issue by coren-frankel** [m-smith15/webdev_flashcards#21]
After some light research, I found the Bootstrap web font CDN to be a very clean way to use Bootstrap Icons without the clunky SVG elements in the HTML. 

We should add the web font CDN to index.html's head if it is not already done, and replace all bootstrap SVGs with their `<i>` element counterpart from the [Bootstrap](https://icons.getbootstrap.com/) library (i.e. apply `<i class="bi bi-arrow-left-circle"></i>` for the back buttons on Create.js and Edit.js).

This is a good first issue, pretty light if you search for all svgs hiding in the frontend with your IDE. Feel free to comment or reach out to me with questions or suggestions.

**Comment by Vinitvh** [comment]
Hi @coren-frankel, I would like to work on this issue.

**Comment by coren-frankel** [comment]
Sounds good @Vinitvh! Glad to have you join the WDF project! I've assigned the issue to you. Note that I have a current PR awaiting review that has changes in the Practice.js and CardList.jsx files. Consider avoiding any changes in either of those files until the merge.

I look forward to seeing your PR soon!

**Comment by Vinitvh** [comment]
@coren-frankel sure. Thanks for the heads up.

**Comment by m-smith15** [comment]
Hey @Vinitvh - I just approved @coren-frankel's changes in that PR. Pull down those changes whenever you continue working on this! :)
