### ISSUE TITLE
Convert light mode background colors to hex with alpha code to match dark mode counterpart

### ISSUE THREAD

**Issue by coren-frankel** [m-smith15/webdev_flashcards#24]
The recent addition of Dark/Light mode uses `lightgrey` for the new light mode background color.
When toggling between the colors you will notice that dark mode -- which inherits the original theme -- has an opacity on the footer.

Dark:
![Dark Mode WDF](https://user-images.githubusercontent.com/104476731/224511721-2f5b0d00-dd60-4c91-8319-abcb89360a50.png)

Light:
![Light Mode WDF](https://user-images.githubusercontent.com/104476731/224511686-233cd7e1-bd86-460f-a0ec-4246f48a26e1.png)

This is a great first issue that I would like to save for someone who wants to join in on WDF! 
<details>
<summary>Need a hint?</summary>
<br>
Translate 'lightgrey' into a hexadecimal value then apply an alpha value to it to match the dark mode transparency for the Header and Footer theme change.
</details>

I am happy to answer any questions about this one!

**Comment by dialejo24** [comment]
do you need to get rid of the opacity so that the footer background is really black ?

**Comment by coren-frankel** [comment]
I think the opacity looks good on the dark footer and header. Instead, I would love to see the light mode also have this opacity. It's not obvious at a glance, but the header shares the same opacity as the footer, so this would be best applied to the header as well when making the change.

Let me know if you need some direction on how to convert the `lightgrey` to hex. Otherwise, utilizing the same alpha code that the dark theme currently uses should easily attach to it.

I don't want to take to much fun out of solving this issue, but I'm happy to advise further if you want.

Should I assign this one to you @dialejo24?

**Comment by dialejo24** [comment]
i would like to solve this issue and make my first contribution

**Comment by coren-frankel** [comment]
Have at it, my friend!

I've assigned it to you.

Be aware that there is a pending PR in the pipeline, #23. It does not affect code within the Header component, but you will need to pull the `master` branch before submitting your PR after it is merged to avoid any potential conflict.

**Comment by dialejo24** [comment]
do i have to add the opacity to the header and footer in lightmode, right?

**Comment by coren-frankel** [comment]
Yes, please.

**Comment by m-smith15** [comment]
Closing issue as fixed! Not sure why it didn't close when I merged the PR...but hey we're all learning.
