### ISSUE TITLE
Move acknowledgements to new page

### ISSUE THREAD

**Issue by m-smith15** [m-smith15/webdev_flashcards#27]
Project is growing, which is a really cool thing! Realizing that keeping a running list of contributors in the footer isn't scalable. 

Would like to add in a dedicated page consisting of "credits" page with links to contributors GitHub and/or LinkedIn based on their pref.

**Comment by coren-frankel** [comment]
🙄 Seems the commit message didn't close this, perhaps because it wasn't in the PR or merge commit message? Ugh. Any way, closing now.
